version: "3"
services:
  fpm:
    image: modicn/php:7.4.23-fpm-alpine3.14-dev
    volumes:
      - .:/app
    working_dir: /app
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
    volumes:
      - ./_docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./_docker/mysql/zz-zz.cnf:/etc/mysql/conf.d/zz-zz.cnf
      - mysql_data:/var/lib/mysql
  nginx:
    image: nginx:1.20-alpine
    depends_on:
      - fpm
    volumes:
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
volumes:
  mysql_data: ~
