version: "3"
services:
  fpm:
    image: modicn/php:7.4.23-fpm-alpine3.14-dev
    volumes:
      - .:/app
    working_dir: /app
  nginx:
    image: nginx:1.20-alpine
    depends_on:
      - fpm
    volumes:
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
